---
- name: Configure Access Switches Dynamically
  hosts: switches
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - name: 1. Create VLANs dynamically from vars
      cisco.ios.ios_vlans:
        config: "{{ vlans }}"
        state: merged
    - name: 2. Bind Physical Interfaces to EtherChannel
      cisco.ios.ios_lag_interfaces:
        config:
          - name: 1
            members: >- 
              {{ switches_config[inventory_hostname].etherchannel_members }}
        state: merged
    - name: 3. Configure EtherChannel (Port-Channel 1) as Trunk
      cisco.ios.ios_config:
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - switchport trunk allowed vlan "{{ vlans | map(attribute='vlan_id') |
            join(',') }}"
        parents: interface Port-channel1
    - name: 4. Configure Access Ports & Port Security dynamically
      cisco.ios.ios_config:
        lines:
          - switchport mode access
          - switchport access vlan {{ item.vlan }}
          - switchport port-security
          - switchport port-security maximum 1
          - switchport port-security violation shutdown
          - switchport port-security mac-address sticky
        parents: interface {{ item.name }}
      loop: "{{ switches_config[inventory_hostname].access_ports }}"
